# Generated by Django 5.2.5 on 2025-09-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_rename_title_entry_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='ai_analysis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
